# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mainshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainshow',
            name='brand_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='category_id',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='child_cid1',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='child_cid2',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='child_cid3',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='product_id1',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='product_id2',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='product_id3',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
