# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180507_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='usename',
            new_name='username',
        ),
    ]
