# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180508_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='category',
            new_name='category_id',
        ),
    ]
