# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_goods_new_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='new_category',
            field=models.ForeignKey(default=models.CharField(max_length=16), on_delete=django.db.models.deletion.CASCADE, to='home.FoodType'),
        ),
    ]
