# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_goods_new_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='new_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.FoodType'),
        ),
    ]
