# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_goods_new_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='category_id',
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.FoodType'),
        ),
    ]
